# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Musings of an IT Dove. Ehmm... Falcon, that is.
email:
description: >- # this means to ignore newlines until "baseurl:"
  This site represents the open source blog initiative of SjoerdV.
  I will mainly blog about Microsoft Tech and Powershell code.
  Enjoy!
twitter_username: sjoerddevalk
github_username: SjoerdV
minimal_mistakes_skin: default
search: true

twitter:
  username: "sjoerddevalk"

repository  : "sjoerdv/sjoerdv.github.io" # Git username/repo-name e.g. "mmistakes/minimal-mistakes"
#comments:
#  provider: "utterances"
#  utterances:
#    theme: "github-light" # "github-dark"
#    issue_term: "pathname"
comments:
  provider: "staticman_v2"
  staticman:
    branch: "master"
    endpoint: https://fhq-staticman-p.azurewebsites.net/v3/entry/github/

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "SjoerdV"
  avatar : "/assets/images/Logo.png"
  bio    : "Maybe I'm just like my father, too bold..."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/company/spdevalk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sjoerddevalk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/f4lc0n99/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SjoerdV"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/f4lc0n99/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sjoerddevalk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SjoerdV"

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      sidebar:
        - title: "Role"
          # image: /assets/images/Logo.png
          # image_alt: "logo"
          text: "Microsoft Cloud Productivity & BPM Consultant"
        - title: "Responsibilities"
          text: "Giving it all to improve continuously."
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
