# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Falcon's Nest
email:
url: https://www.spdevalk.nl
og_image: /assets/images/Logo.png
description: >- # this means to ignore newlines until "baseurl: "
  This site represents Sjoerd's open source blog initiative.
  I will mainly write about 'FOSS' Technology subjects. Although in my earlier life my focus was on Microsoft technologies. But maybe I'll present you with something else entirely...
  Some posts will contain code (like Python, Bash and PowerShell).
  Enjoy!
github_username: SjoerdV
minimal_mistakes_skin: dark
search: true

mastodon:
  username: "@sjosjo@mas.to"
  url: https://mas.to/@sjosjo"

comments:
  provider: false # turn off Minimal Mistakes' default comment system
  # your Mastodon host (the server where you have the Mastodon account):
  host: mas.to
  # vanity domain (optional); host will be used if omitted:
  domain: spdevalk.nl
  # your Mastodon username:
  username: sjosjo
  # API token to fetch more than 60 replies to any given blog post (optional):
  #token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  # verified users (optional):
  #verified:
  # - XY@XY.XY
  # default id (serves as a fallback if no id is specified in front-matter):
  id: 114220259572283463
#repository: "sjoerdv/sjoerdv.github.io-comments" # "sjoerdv/sjoerdv.github.io" # Git username/repo-name e.g. "mmistakes/minimal-mistakes"
#comments:
#  provider: "giscus"
#  giscus:
#    repo_id: "R_kgDOKO0Gmg" # Shown during giscus setup at https://giscus.app
#    category_name: "Announcements" # Full text name of the category
#    category_id: "DIC_kwDOKO0Gms4CZDUH" # Shown during giscus setup at https://giscus.app
#    discussion_term: "pathname" # "pathname" (default), "url", "title", "og:title"
#    reactions_enabled: 1 # '1' for enabled (default), '0' for disabled
#    theme: "dark_dimmed" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
#comments:
#  provider: "utterances"
#  utterances:
#    theme: "github-dark" # "github-light"
#    issue_term: "pathname"
#comments:
#  provider: "staticman_v2"
#  staticman:
#    branch: "master"
#    endpoint: https://fhq-staticman-p.azurewebsites.net/v3/entry/github/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Sjoerd de Valk"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Clear, Swift, Analytical, Pragmatic and Safe, Can-Do - preferably Automated."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/company/spdevalk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/f4lc0n99/"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mas.to/@sjosjo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SjoerdV"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/f4lc0n99/"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mas.to/@sjosjo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SjoerdV"

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  stories:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      sidebar:
        - title: "Role"
          # image: /assets/images/Logo.png
          # image_alt: "logo"
          text: "Freelance Microsoft Cloud SaaS & iPaas Solution Consultant and FOSS aficionado"
        - title: "Responsibilities"
          text: "Giving it all to improve continuously."
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  # _stories
  - scope:
      path: ""
      type: stories
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
